services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $project_root: '%kernel.project_dir%'

  Win32ServiceBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Model,Tests,Win32ServiceBundle.php}'


  Win32ServiceBundle\Command\RegisterServiceCommand:
    autowire: true
    calls:
      - ['defineBundleConfig', ['%win32service.config%']]
